services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: task_management_sql_server
    environment:
      SA_PASSWORD: "!D3s4F10j4V4!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
volumes:
  sqlserver_data:
    driver: local