CREATE TABLE TASK (
    id INT PRIMARY KEY IDENTITY(1,1),
    title NVARCHAR(100) NOT NULL,
    description NVARCHAR(500),
    create_date DATETIME NOT NULL,
    status NVARCHAR(20) NOT NULL CHECK (status IN ('CREATED', 'PENDING', 'IN_PROGRESS', 'DONE'))
);